### ISSUE TITLE
Linking fails with error -1

### ISSUE THREAD

**Issue by mclane** [n8henrie/rust-stm32#1]
I have tried to build the program using rustc 1.39.0-nightly (eb48d6bde 2019-09-12); however linking fails with error rust-lld: error: no memory region specified for section '.ARM.exidx'
I just found out that changing the version of cortex-m-rt from 0.6.7 to 0.6.10 in Cargo.toml fixes the issue.

**Comment by n8henrie** [comment]
Thanks for the heads up!
